### ISSUE TITLE
Delacorte/RH

### ISSUE THREAD

**Issue by v1s-page** [almossawi/big-five-publishers#10]
Delacorte is with RHCB, not Random House. It's a YA and MG imprint.

**Comment by almossawi** [comment]
Thanks 👍 

Fixed, updated, and credited you.

<img width="1058" alt="Screen Shot 2020-08-16 at 5 55 12 PM" src="https://user-images.githubusercontent.com/980049/90348204-bc6f3480-dfe9-11ea-9f20-6adb6f652710.png">
