### ISSUE TITLE
MCD Books

### ISSUE THREAD

**Issue by scottcbest** [almossawi/big-five-publishers#12]
Hello! First off, so much thanks for such an excellent chart! Am referring to it all the time, terrifically useful.

Wanted to bring one to your attention: MCD Books which I think is a peer of FSG Originals beneath the FSG group. Only reason I know of it: friend of mine is on their 2021 release calendar. :-)

Hope this is useful, thanks again.

**Comment by almossawi** [comment]
Thanks, Scott. Grateful :) I've added MCD Books and credited you for it.

Congrats to your friend! It looks like a fantastic imprint. 🎉

<img width="1094" alt="Screen Shot 2020-08-29 at 6 12 15 PM" src="https://user-images.githubusercontent.com/980049/91649008-b8003e00-ea23-11ea-9db4-6fbdebc72fb7.png">
