### ISSUE TITLE
Faber and Faber

### ISSUE THREAD

**Issue by CHsiangBooksInc** [almossawi/big-five-publishers#13]
I'm pretty certain Faber and Faber are no longer distributed by FSG/Macmillan anymore, in the States, at least.
Looks like the aren't in the Big Five at all. PGW?

**Comment by almossawi** [comment]
Right you are. I'd probably seen it mentioned here and didn't click through to see that it wasn't listed as an imprint anymore:
https://us.macmillan.com/publishers/

Updated and credited you for the fix 👍

**Comment by CHsiangBooksInc** [comment]
Wow, thanks for the prompt reply and action. As a bookseller and buyer, I have been using your lovely chart for years. Keep up the good work!

A thing though: is it searchable? It would be even handier if a untechnical clod like me could type up a name and have it pop up in the chart.

 

Thank you,
Chris Hsiang



Books Inc.
Restock Buyer
1491 Shattuck
Berkeley, CA
94709

(510) 525-7777
pronouns: he/him/his

**Comment by almossawi** [comment]
My pleasure, Chris!

I've filed #14 (Make it Searchable), so that I don't forget about it. You're right, it would be nice to have a search box on the page. You can currently search using `Ctrl/Command + F` since all the labels are text, albeit it's not an ideal experience.
