### ISSUE TITLE
Missing imprint for HarperCollins Children’s 

### ISSUE THREAD

**Issue by KellyZhangYL** [almossawi/big-five-publishers#18]
Quill Tree is a HC imprint that publishes diverse children's books. It should go under HarperCollins Children's branch.

**Comment by almossawi** [comment]
Thank you! Fixed and updated.

I credited you in the footer as __KellyZhangYL__. Happy to change that if you like. :)

<img width="1110" alt="Screenshot 2023-04-27 at 7 54 52 AM" src="https://user-images.githubusercontent.com/980049/234902637-e0a84c01-4443-4d1d-898b-2b931c2bb1ff.png">

**Comment by KellyZhangYL** [comment]
Hi Ali,
Thank you for your super quick response. Looks great!
Thank you so much for creating this amazing graphic--as a writer, I
personally found it very helpful and enlightening!

You can credit me as Kelly Zhang :)

Cheers,

Kelly

**Comment by almossawi** [comment]
Of course. So glad to hear it :)

> You can credit me as Kelly Zhang :)

Done, and updated!
