### ISSUE TITLE
Penguin needs updated

### ISSUE THREAD

**Issue by toryhallelujah** [almossawi/big-five-publishers#19]
They're now distributing Disney/Hyperion + related imprints as of spring 2023. Thanks!

**Comment by almossawi** [comment]
Are they only distributed by PRH or also owned by it? The current graphic only shows imprints owned by a publisher.

**Comment by caro227** [comment]
In Random House Children's Books you're missing imprints Anne Schwartz Books and Random House Studio. These two newish imprints came about after Schwartz and Wade split. https://www.publishersweekly.com/pw/by-topic/childrens/childrens-industry-news/article/85723-anne-schwartz-books-to-set-sail-this-summer.html

Such a cool graphic. Thanks!

**Comment by almossawi** [comment]
So sorry, @caro227. I thought if I kept looking away every day, my list of unread emails would get shorter. I'll add those today, thank you!

**Comment by almossawi** [comment]
Updated, thank you! Let me know if you'd like me to credit a different name.

**Comment by almossawi** [comment]
@caro227 Updated, thank you! Let me know if you'd like me to credit a different name.

**Comment by caro227** [comment]
Caroline Rose would be great. Thanks so much creating and maintaining this!Sent from my iPhoneOn Aug 25, 2023, at 10:30 PM, Ali Almossawi ***@***.***> wrote:﻿
@caro227 Updated, thank you! Let me know if you'd like me to credit a different name.

**Comment by almossawi** [comment]
Done!
