### ISSUE TITLE
Correction for Hachette

### ISSUE THREAD

**Issue by freelanceastro** [almossawi/big-five-publishers#2]
This is a great chart! It's not on their website yet, but there's a new division of Hachette, Perseus Books, which Hachette acquired in April:
http://www.publishersweekly.com/pw/by-topic/industry-news/publisher-news/article/69818-sale-of-perseus-to-hachette-and-ingram-completed.html
http://www.nytimes.com/2016/03/02/business/media/hachette-again-reaches-deal-with-perseus-books.html
http://www.adweek.com/galleycat/hachette-has-acquired-perseus/118445
http://www.perseusbooksgroup.com/assets/HBG-Perseus-Press-Release_FINAL-3-1-16.pdf
Perseus, in turn, has nine imprints. Looks like those are:
- Avalon Travel
- Basic Books
- Basic Civitas
- Da Capo Press
- Da Capo Lifelong Books
- PublicAffairs
- Running Press
- Seal Press
- Westview Press

**Comment by almossawi** [comment]
Wonderful, thanks! Added and deployed 👍

**Comment by almossawi** [comment]
Will keep an eye out for your forthcoming book. Sounds fascinating.
