### ISSUE TITLE
PRH Updates

### ISSUE THREAD

**Issue by Mbelford91** [almossawi/big-five-publishers#21]
Here are a few small changes to PRH!

DAW is no longer an imprint at Penguin Random House (they've moved to Astra House)
"Random House Worlds" and "Inklore" are now imprints under Random House (under PRH). They've also acquired Boom! Studios, but that deal was just announced and won't be final for months.

**Comment by almossawi** [comment]
Thanks so much! I'm pushing those updates in a second.

Did you want me to credit you as Mbelford91?

**Comment by Mbelford91** [comment]
Actually could you credit me as Matt Belford? Thanks for the swift reply
here! And doubly so for creating this tool. I found it a few years ago and
it continues to be a resource I rely on!

**Comment by almossawi** [comment]
Glad to hear it! Done and updated.
