### ISSUE TITLE
HarperOne Group

### ISSUE THREAD

**Issue by sam-tatum** [almossawi/big-five-publishers#9]
Hi there,

Big fan of this. Super helpful!

A couple imprints changed names/were recently created under HarperCollins:

Rayo -> [HarperCollins Español](https://www.facebook.com/HarperCollinsEs/)
HarperElixir -> [HarperOne](https://harperone.com/)
[HarperVia](https://www.facebook.com/HarperVia-Books-2201858813186776/) is new.

The above three imprints, in addition to Amistad, now make up the HarperOne Group.

**Comment by almossawi** [comment]
Hi, there. Thank you! I updated the page and credited you in the footer 👍 

Are Rayo and HarperCollins Español separate imprints?

<img width="1048" alt="Screen Shot 2019-12-13 at 2 39 42 PM" src="https://user-images.githubusercontent.com/980049/70836896-9ccaa100-1db6-11ea-8e7a-ed9ab07387bf.png">

**Comment by sam-tatum** [comment]
Hi!

Looks good—and no, HarperCollins Español is the new name for Rayo.

**Comment by almossawi** [comment]
Sounds good, thanks!
